Feature: Add API for certificates
sandwave-io/realtimeregister-php pull request #58
Opened 2022-03-31 13:24 UTC by jfabot

Added an API for certificates
Activated calls:
- list certificates
- download certificate
- list DCV email addresses
- list products
- get product
- get certificate
- request certificate
- renew certificate
- reissue certificate
- revoke certificate
- send subscriber agreement
- add note
- schedule validation call
- import certificate

2022-04-01 06:51 UTC, thijswiersema commented on src/Api/CertificatesApi.php
> +        $this->client->post('/v2/ssl/certificates', $payload);
Already discussed/talked about, but as a reminder the suggestion to return the created process ID. (Same for the renew request).

2022-04-01 06:51 UTC, thijswiersema commented on src/Api/CertificatesApi.php
> +        $this->client->post('/v2/ssl/certificates', $payload);
Already discussed/talked about, but as a reminder the suggestion to return the created process ID. (Same for the renew request).

2022-04-06 11:23 UTC, thijswiersema submitted a review, later dismissed

2022-04-06 12:27 UTC, stephanvdhorn requested changes

2022-04-06 12:27 UTC, stephanvdhorn commented on src/Domain/Product.php
> +    private function __construct(
https://dm.realtimeregister.com/docs/api/ssl/products/get

features, requiredFields, optionalFields, includedDomains and maxDomains are all optional, shouldn't these be nullable?

2022-04-06 12:56 UTC, stephanvdhorn approved these changes

2022-04-06 12:58 UTC, thijswiersema approved these changes

2022-04-06 12:58 UTC, merged